### ISSUE TITLE
great debug mode

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright-runner#14]
We have all of the pieces for a great debugging experience, but we need to tie them together.
- Headful mode
- Run a single test
- Connect to chrome/node via vscode

**Comment by jperl** [comment]
Another important thing for debugging is to be able to watch the test steps happen at a human speed. 

I often use slowMo to watch a test, however the slow down behavior is not exactly what I would want.  It seems to slow down every operation instead I just want it to pause 500ms before each action (`click` / `fill` / `type`).

**Comment by JoelEinbinder** [comment]
`slowMo` is a brute force hack. We can do something more intelligent based on calls into playwright, or even lines of your test. There is some fancy code in playwright's internal test runner that runs a test, opens devtools on it, and prints every line of the test function as it is run. We could probably extend that to wait 1 second between lines of your test.
