### ISSUE TITLE
Incremental progress reporting

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright-runner#2]
e2e tests are slower, so I'd like to see test cases (or at least their failures) being reported as they run.

**Comment by dgozman** [comment]
The last one. However, it would probably be `it('should work', ({page, step}) => {...})`

**Comment by celeryclub** [comment]
Has any thought been given to an automatic log of commands performed by Playwright? I implemented this in a project. It's modeled after Cypress's in-browser command log. The dots are yellow while pending and then green on success or red on failure.

https://share.getcloudapp.com/OAubBAbv

My current implementation is a bit hacky (see https://github.com/microsoft/playwright/issues/1654), but I'm curious what you think of this general idea.

**Comment by dgozman** [comment]
@celeryclub Yep, we are thinking about this. The new `Logger` api in Playwright should be able to provide such a log, and test runner will be able to consume it.
