### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright-runner#25]
Right now there is an `@types/jest` packages that adds definitions for `it`/`describe`/`expect` into the global scope. This doesn't work for us, because our `it` has a state as its first argument, instead of a doneCallback.

The unit mode and e2e mode require different types, because the state in e2e mode contains a `page`, whereas the state in unit mode does not.

Ideally these types wouldn't pollute your apps global scope. So you can only use `it` from within `.spec.js` files.

**Comment by lencioni** [comment]
Beyond not polluting the global scope, it would be great if the types were also able to be contained from of other non-playwright jest tests.
