### ISSUE TITLE
getting started template

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright-runner#27]
I'd like to have a single command to run like `npx setup-playwright` that installs all dependencies, adds a jest.config.js, tsconfig.json, github actions, and a sample test.

**Comment by jperl** [comment]
Happy to transfer [create-playwright](https://www.npmjs.com/package/create-playwright) to you. When we built `create-qawolf` initially we were going to make it generic like `playwright-ci` but decided to just build `create-qawolf` instead.

With that name users can run `npm init playwright` and `yarn create playwright`.

**Comment by mxschmitt** [comment]
Any plans already in mind how this should be implemented? Maybe https://yeoman.io or probably thats too much for that.

I though about providing name as a parameter or via the stdin and then just copy the file inside the new folder. Yeomans templating / str/replace is quite nice.

**Comment by JoelEinbinder** [comment]
I haven't played around with yeoman, so I'm not sure what this gives us. I think we should build what the output should look like first, and then decide how heavy the template generator needs to be. It might be as simple as copying some files into the cwd.
