### ISSUE TITLE
Timeout errors

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright-runner#46]
For reference, see https://github.com/microsoft/playwright/issues/2031

This piece of code will not work when running inside Jest:

```javascript
const playwright = require('playwright');
try {
  await page.waitForSelector('.foo');
} catch (e) {
  if (e instanceof playwright.errors.TimeoutError) {
    // Do something if this is a timeout.
  }
  } else {
    console.log(err);
  }
}
```

It is possible that the TimeoutError is a different instance because Jest test cases is run inside a vm context, whereas PlaywrightRunnerE2E runs in Node.js.

This does work:

```javascript
if (err.name === 'TimeoutError')
```

Note: Have not tested this with playwright-runner, but just assuming this is a problem here as well since it was with jest-playwright.

**Comment by mxschmitt** [comment]
Would be awesome to fix this upstream in Jest. Simen has already a PR open to fix that.
https://github.com/facebook/jest/pull/5995
or
https://github.com/facebook/jest/pull/8220
cc @SimenB

**Comment by SimenB** [comment]
Agreed, I haven't been able to make the faked `instanceof` check work though. My current approach is hoping https://github.com/nodejs/node/issues/31852 is fixed

**Comment by JoelEinbinder** [comment]
This shouldn't be a problem with the e2e runner, because we don't use vm anywhere.

**Comment by thernstig** [comment]
So e2e runner is not using Jest to run test cases?

**Comment by JoelEinbinder** [comment]
> So e2e runner is not using Jest to run test cases?

Correct. The e2e test runner runs tests in a single node process. We can do this because all of the important code being tested is in the website running in the browser. The code in node is just the small bits used to drive the test.

**Comment by thernstig** [comment]
Ok - I will have to look into the playwright-runner e2e test runner later. Maybe I misunderstand, but I am using Jest for much more such as reporters, being able to customize runner options and many, many other of Jest's features (expect statements) etc. And I want to use Jest to run them in parallell, taking the caching. performance (run failed first) etc. into account.
